services:
  bot-mnamer:
    image: christt105/mnamer-telegram:latest
    container_name: bot-mnamer
    restart: unless-stopped
    env_file:
      - .env
    user: "${PUID:-1000}:${PGID:-1000}"
    volumes:
      - ./appdata:/data
      - ./media:/media
